# CHAPTER 03. 신경망

In [ ]:
# 3.3 다차원 배열의 계산

In [ ]:
# 3.3.1 다차원 배열 

In [5]:
# 1차원
import numpy as np
A = np.array([1,2,3,4])
print(A)

print(np.ndim(A))

print(A.shape)

print(A.shape[0])

[1 2 3 4]
1
(4,)
4


In [8]:
# 2차원
B = np.array([[1,2],[3,4],[5,6]])
print(B)

print(np.ndim(B))
print(B.shape)

[[1 2]
 [3 4]
 [5 6]]
2
(3, 2)


In [ ]:
# 3.3.2 행렬의 곱

In [11]:
A = np.array([[1,2],[3,4]])
print(A.shape)

B = np.array([[5,6],[7,8]])
print(B.shape)

np.dot(A,B)

(2, 2)
(2, 2)


array([[19, 22],
       [43, 50]])

In [ ]:
# 3.3.3 신경망에서의 행렬 곱

In [12]:
X = np.array([1,2])
print(X.shape)

(2,)

In [14]:
w = np.array([[1,3,5],[2,4,6]])
print(w)
print(w.shape)

[[1 3 5]
 [2 4 6]]
(2, 3)


In [15]:
Y = np.dot(X,w)
print(Y)

[ 5 11 17]
