# CHAPTER 03. 신경망

In [ ]:
# 3.4 3층 신경망 구현하기

In [ ]:
# 3.4.1 표기법 설명

In [ ]:
# 3.4.2 각 층의 신호 전달 구현하기

In [5]:
import numpy as np

X = np.array([1.0,0.5])
w1 = np.array([[0.1,0.3,0.5],[0.2,0.4,0.6]])
b1 = np.array([0.1,0.2,0.3])

print(w1.shape)
print(X.shape)
print(b1.shape)

(2, 3)
(2,)
(3,)
[0.3 0.7 1.1]


In [9]:
def sigmoid(x):
    return 1/(1+np.exp(-x))

A1 = np.dot(X,w1) + b1
z1 = sigmoid(A1)
print(A1)
print(z1)

[0.3 0.7 1.1]
[0.57444252 0.66818777 0.75026011]


In [11]:
# 1층에서 2층으로의 신호 전달

w2 = np.array([[0.1,0.4],[0.2,0.5],[0.3,0.6]])
b2 = np.array([0.1,0.2])

print(z1.shape)
print(w2.shape)
print(b2.shape)

A2 = np.dot(z1,w2) + b2
z2 = sigmoid(A2)

(3,)
(3, 2)
(2,)


In [13]:
# 2층에서 출력층으로의 신호 전달
def identity_function(x):
    return x

w3 = np.array([[0.1,0.3],[0.2,0.4]])
b3 = np.array([0.1,0.2])

A3 = np.dot(z2,w3) + b3
Y = identity_function(A3)

In [ ]:
# 3.4.3 구현 정리

In [14]:
def init_network():
    network = {}
    network['W1'] = np.array([[0.1,0.3,0.5],[0.2,0.4,0.6]])
    network['b1'] = np.array([0.1,0.2,0.3])
    network['W2'] = np.array([[0.1,0.4],[0.2,0.5],[0.3,0.6]])
    network['b2'] = np.array([0.1,0.2])
    network['W3'] = np.array([[0.1,0.3],[0.2,0.4]])
    network['b3'] = np.array([0.1,0.2])
    
    return network

def forward(network, x):
    W1, W2, W3 = network['W1'], network['W2'], network['W3']
    b1, b2, b3 = network['b1'], network['b2'], network['b3']
    
    a1 = np.dot(x, W1) + b1
    z1 = sigmoid(a1)
    a2 = np.dot(z1, W2) + b2
    z2 = sigmoid(a2)
    a3 = np.dot(z2, W3) + b3
    y = identity_function(a3)
    
    return y

network = init_network()
x = np.array([0.1,0.5])
y = forward(network,x)
print(y)

[0.31234736 0.6863161 ]
