# CHAPTER 03. 신경망

In [ ]:
# 3.5 출력층 설계하기

In [ ]:
# 3.5.1 항등함수와 소프트맥스 함수 구현하기

In [2]:
import numpy as np
a = np.array([0.3,2.9,4.0])

exp_a = np.exp(a)
print(exp_a)

[ 1.34985881 18.17414537 54.59815003]


In [3]:
sum_exp_a = np.sum(exp_a)
print(sum_exp_a)

74.1221542101633


In [4]:
y = exp_a / sum_exp_a
print(y)

[0.01821127 0.24519181 0.73659691]


In [5]:
def softmax(a):
    exp_a = np.exp(a)
    sum_exp_a = np.sum(exp_a)
    y = exp_a / sum_exp_a
    
    return y

In [ ]:
# 3.5.2 소프트맥스 함수 구현 시 주의점

In [7]:
a = np.array([1010,1000,990])
np.exp(a) / np.sum(np.exp(a))

c = np.max(a)
a - c

np.exp(a - c) / np.sum(np.exp(a - c))

<ipython-input-7-d840f8928d85>:2: RuntimeWarning: overflow encountered in exp
  np.exp(a) / np.sum(np.exp(a))
<ipython-input-7-d840f8928d85>:2: RuntimeWarning: invalid value encountered in true_divide
  np.exp(a) / np.sum(np.exp(a))


array([9.99954600e-01, 4.53978686e-05, 2.06106005e-09])

In [8]:
def softmax(a):
    c = np.max(a)
    exp_a = np.exp(a-c)
    sum_exp_a = np.sum(exp_a)
    y = exp_a / sum_exp_a
    
    return y

In [ ]:
# 3.5.3 소프트맥스 함수의 특징

In [9]:
a = np.array([0.3, 2.9, 4.0])
y = softmax(a)
print(y)

np.sum(y)

[0.01821127 0.24519181 0.73659691]


1.0

In [ ]:
# 3.5.4 출력층의 뉴런 수 정하기 